### ISSUE TITLE
[improvement] responsiveness of welcome page

### ISSUE THREAD

**Issue by mounikakrishna8** [tomasdepiano/Chat-App#59]

**Comment by Sureshwebdeveloper** [comment]
Hai my name Suresh,
I am front end reacts developer could you assign this task to me? 
and can i know about what sizes are you need to create responsive ness like mobile only?

**Comment by tomasdepiano** [comment]
POST MVP

**Comment by Sureshwebdeveloper** [comment]
Hey If you Completed the design task  ? If Not Complete Please Assign To Me
